#
# Splunk app configuration file
#

[install]
is_configured = 0

[ui]
is_visible = 1
label = BADRCM

[launcher]
author = brett.whynot@gmail.com
description = Brett Adams' Dangerous REST Config Manager
version = 0.1.2

[package]
id = badrcm

[triggers]
reload.badrcm = rest_endpoints 